### ISSUE TITLE
Would it be possible to use two pi Picos as a Midi bridge between two host devices?

### ISSUE THREAD

**Issue by ramphands** [rsta2/pico#1]
Hello there!
First of all, thank you so much for the project.

My intention is to get two RPi 3s communicating via USB-Midi.  I am aware that there are devices which function as a bridge to allow two hosts to connect, and I wondered if it would simply be a case of having two Picos with the UART Tx Rx pins connected.  Would that be correct?

Many thanks!

**Comment by rsta2** [comment]
Yes, this should work. You have to cross-connect the UART-TX/-RX lines and connect GND of both Picos. The power pins (VSYS, VBUS) must NOT be connected, because the Picos will be powered via USB. Thanks for appreciating my project!

**Comment by ramphands** [comment]
Thank you so much for such a prompt reply!  
I shall test it and let you know the results.
All the best

**Comment by rsta2** [comment]
@ramphands Did this work for you?

**Comment by ramphands** [comment]
Irritatingly I haven't been able to find a second Pi Pico so I haven't had
a chance to test it yet.

**Comment by rsta2** [comment]
Understood. Thanks for info.

**Comment by ramphands** [comment]
However, I must add that I've been using the code for the one Pico that I do have, interfacing between a RPi3 (outputting USBMidi) and another RPi3 running Minidexed (using the UART pins) and it's working wonderfully.

**Comment by rsta2** [comment]
Good to know. Thanks!

**Comment by ramphands** [comment]
Seeing as I still haven't been able to get another Pico, I ended up creating a hat/shield for the Pi with your code-laden Pico attached.  Actually works out more elegantly than I would have thought!
https://github.com/ramphands/Minidexed-Shield
Thank you again so much for the code - it works like a charm.

**Comment by rsta2** [comment]
You are welcome. Your shield looks great!
