### ISSUE TITLE
How to install MIDI adapter?

### ISSUE THREAD

**Issue by fastKsad** [rsta2/pico#3]
Hello, I am new with all of this things related to RB Pico, and I saw this code of "midi_adapter/" that can help me in a project but I don't know how to make it work on my RB pico. 
I will be very glad if somebdy helps me.

**Comment by rsta2** [comment]
Just download the *midi_adapter.zip* file from the [Releases page](https://github.com/rsta2/pico/releases), unpack it, connect your Raspberry Pi Pico to a desktop computer, while the BOOTSEL button is pressed on it, and copy the file *midi_adapter.uf2* from the archive to the appearing Pico drive. After a few seconds the program has been flashed and is ready to be used.

**Comment by rsta2** [comment]
I think, this question has been answered and the issue can be closed.
