### ISSUE TITLE
Schematics / Hardware requirements

### ISSUE THREAD

**Issue by atulrnt** [rsta2/pico#5]
Hi, the Midi Adapter Flex sounds exactly like what I'm looking for (a MIDI USB interface allowing me to send MIDI message to and from my computer).

I'm just wondering what the hardware part should look like as I can't find any schematics or anything hardware related in this repo.

Thank you in advance for pointing me out the right direction!

**Comment by rsta2** [comment]
I do not have a drawn schematics image, but wiring is simple, as described in 
the README:

> serial interface via GP0 (UART0 TX)/GP1 (RX) and/or 
> GP4 (UART1 TX)/GP5 (RX)
>
> ...
>
> The Raspberry Pi Pico is powered via USB, the VSYS or VBUS pins 
> must NOT be connected!

You also have to connect the ground for each serial interface.

**Comment by atulrnt** [comment]
Thanks for answering so quickly!

In that case, should I connect the MIDI female connector directly to the UART pins? 
No optocoupler, resistors or anything like that?

**Comment by rsta2** [comment]
What do you want to connect? On one side there is the computer via USB. What 
is on the other side? If it is a keyboard with a normal DIN serial MIDI jack, 
it is right, you need a small circuit with an optocoupler. Unfortunately I do 
not have it by hand. Perhaps you can find it on the Internet.

**Comment by rsta2** [comment]
Perhaps the circuit in [this article](https://diyelectromusic.com/2023/12/12/raspberry-pi-zero-midi-pcb/) can help you. It describes a MIDI interface for the Raspberry Pi Zero, but the two parts of the circuit for MIDI IN and OUT should re-usable for the Raspberry Pi Pico. Please note that the pins of the Pico can only handle 3.3V levels not 5V.

For explanation: I used the Pico with my software only to connect a Raspberry Pi SBC to a PC. In this case a converter circuit is not necessary. Also I'm a software developer, hardware is not my business.

**Comment by atulrnt** [comment]
Thank you, this exactly what I needed!
